---

## Site settings
title: "Jana Wagemaker"
description: "Personal website and curriculum vitae of Nicolas “Niols” Jeannerod."

## Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

nav:
  - name: About
    url: /index.html

  - name: Curriculum Vitæ
    url: /curriculum-vitae.html

  - name: PhD Thesis
    url: /phd-thesis.html

  - name: Talks
    url: /talks.html

  - name: Publications
    url: /publications.html

  - name: Teaching
    url: /teaching.html
